version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace/backend
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=appdb;Username=dev;Password=password

  frontend:
    image: node:20
    working_dir: /workspace/frontend
    volumes:
      - .:/workspace
    command: sh -c "npm install && npm start"
    ports:
      - 4200:4200

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
